on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, edited ]
name: conventional-release-labels
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels
